"""Render figures/positional_distribution.png for divergence_analysis.md.

Counts, per residue position, how many of the 92 designs differ from the
training-set consensus.
"""
import collections

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BLUE = "#256abf"
INK = "#2c2c2a"
MUTED = "#6f6f6a"
PROMPT_BAND = "#f0efec"

cons = open("design/consensus.txt").read().strip()
designs = [l.strip() for l in open("design/design.txt") if l.strip()]
counts = collections.Counter(
    p + 1 for s in designs for p in range(237) if s[p] != cons[p]
)
x = range(1, 238)
y = [counts.get(i, 0) for i in x]

fig, ax = plt.subplots(figsize=(7.2, 2.6))

# the prompt occupies residues 1-64; shade it so the reader can see that every
# bar falls inside it without needing a second colour
ax.axvspan(0.5, 64.5, color=PROMPT_BAND, zorder=0, linewidth=0)
ax.bar(x, y, width=0.85, color=BLUE, zorder=2, linewidth=0)

ax.set_xlim(0.5, 237.5)
ax.set_ylim(0, 72)
ax.set_xlabel("residue position", color=INK)
ax.set_ylabel("designs differing\nfrom consensus", color=INK)
ax.set_xticks([1, 36, 64, 100, 150, 200, 237])
ax.set_yticks([0, 20, 40, 60])

for side in ("top", "right"):
    ax.spines[side].set_visible(False)
for side in ("left", "bottom"):
    ax.spines[side].set_color(MUTED)
ax.tick_params(colors=MUTED, length=3)
for label in ax.get_xticklabels() + ax.get_yticklabels():
    label.set_color(INK)

ax.annotate("prompt\nresidues 1-64", xy=(18, 44), ha="center", va="bottom",
            color=MUTED, fontsize=8)
ax.annotate("generated by the model, residues 65-237", xy=(152, 44),
            ha="center", va="bottom", color=MUTED, fontsize=8)
# position 47 alone accounts for 61 of the 188 substitutions, so name it rather
# than leaving the reader to measure against gridlines that aren't there
ax.annotate("47", xy=(47, 63), ha="center", color=INK, fontsize=8)

fig.tight_layout()
fig.savefig("figures/positional_distribution.png", dpi=220,
            facecolor="white", bbox_inches="tight")
print("wrote figures/positional_distribution.png",
      f"({sum(y)} substitutions across {sum(1 for v in y if v)} positions)")
